-- {
--       id: "3ef36f8d-57d3-4b56-8b4e-466e2818158b",
--       date: "2024-03-27",
--       amount: 6375530,
--       memo: undefined,
--       cleared: "cleared",
--       approved: false,
--       flag_color: undefined,
--       account_id: "af9cbe01-6482-4cf0-8ea4-7da80bd3c7fd",
--       payee_id: "f59fc7b5-4b9a-4d0c-a63b-69c4ae02fa73",
--       category_id: undefined,
--       transfer_account_id: undefined,
--       transfer_transaction_id: undefined,
--       matched_transaction_id: undefined,
--       import_id: "YNAB:6375530:2024-03-27:1",
--       import_payee_name: "SMRT SMRT ST-Y4T4S5W0H3D9 ADVENT CLEANERS",
--       import_payee_name_original: "SMRT SMRT ST-Y4T4S5W0H3D9 ADVENT CLEANERS",
--       debt_transaction_type: undefined,
--       deleted: false,
--       account_name: "wf ops",
--       payee_name: "SMRT SMRT ST-Y4T4S5W0H3D9 ADVENT CLEANERS",
--       category_name: "Uncategorized",
--       subtransactions: [],
--     }
CREATE TABLE
  IF NOT EXISTS ynab_transactions (
    id uuid PRIMARY KEY,
    date DATE,
    amount double precision,
    memo TEXT,
    cleared TEXT,
    approved BOOLEAN,
    flag_color TEXT,
    account_id TEXT,
    payee_id TEXT,
    category_id TEXT,
    transfer_account_id TEXT,
    transfer_transaction_id TEXT,
    matched_transaction_id TEXT,
    import_id TEXT,
    import_payee_name TEXT,
    import_payee_name_original TEXT,
    debt_transaction_type TEXT,
    deleted BOOLEAN,
    account_name TEXT,
    payee_name TEXT,
    category_name TEXT
  );
