on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install

      - name: Cache bun installs
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-${{ matrix.bun }}-bun-

      - run: bun run index.ts
        env:
          RAMP_CLIENT_ID: ${{ secrets.RAMP_CLIENT_ID }}
          RAMP_CLIENT_SECRET: ${{ secrets.RAMP_CLIENT_SECRET }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      # - name: Run script
      #   run: bun run main
      #   env:
      #     RAMP_CLIENT_ID: ${{ secrets.RAMP_CLIENT_ID }}
      #     RAMP_CLIENT_SECRET: ${{ secrets.RAMP_CLIENT_SECRET }}
      #     POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
